### ISSUE TITLE
CRASH DURING WorldGen

### ISSUE THREAD

**Issue by trismegistis** [RaiderofRamen/RF-Quarry#1]
Mod crashes world. Crashes when generating world, even on latest update. Probably conflicting with another mod (have 290+ mods X])

**Comment by RaiderofRamen** [comment]
If you could give me your crash log, that would be much appreciated.

**Comment by trismegistis** [comment]
I will sometime. Sorry removed it and it's been working great. I'll try
next update you release and see if I can bring it back :]
