### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by plaguewolf** [RaiderofRamen/RF-Quarry#2]
during worldgen im getting a crash that i suspect is related to your mod

IllegalArgumentException: bound must be positive

crash log;

http://pastebin.com/v6Ud0X5F

**Comment by sfPlayer1** [comment]
This is caused by https://github.com/RaiderofRamen/RF-Quarry/blob/master/src/main/java/raideroframen/rfquarry/Reference.java#L62

It has min and max swapped, causing it to quantity from 1 to 0 ascending, which is impossible.

**Comment by jsaggers** [comment]
I also get this same crash. Any chance of a fix, update.

**Comment by RaiderofRamen** [comment]
Ah, I'm so sorry for not seeing this sooner! I'll try and get a fix out soon. Thank you, @sfPlayer1 for doing most of the work for me! :+1:
